baby_name/urls.py
from django.urls import path

from baby_name.views.epuration import user_epuration
from .views.add_name import add_name
from .views.evaluation import EvaluationController

from .views.global_leaderboard import global_leaderboard
from .views.home import home
from .views.user_leaderboard import user_leaderboard
from .views.ranking import Ranking
from .views.results import results
from .views.scripts import ScriptController
from .views.vote import Vote

app_name = "baby_name"

urlpatterns = [
    path("", home, name="home"),
    path("epuration/", user_epuration, name="epuration"),
    path("evaluation/delete", EvaluationController.delete, name="evaluation_delete"),
    path("evaluation/update", EvaluationController.get_or_update, name="evaluation_update"),
    path("global_leaderboard/", global_leaderboard, name="global_leaderboard"),
    path("name/new", add_name, name="add_name"),
    path("ranking/", Ranking.form, name="ranking"),
    path("ranking_vote/", Ranking.post, name="ranking_vote"),
    path("results/", results, name="results"),
    path("scripts/", ScriptController.glossary, name="scripts_home"),
    path("scripts/mass-yes/", ScriptController.mass_yes, name="scripts_mass_yes"),
    path("user_leaderboard/", user_leaderboard, name="user_leaderboard"),
    path("vote/", Vote.post, name="vote"),
    path("vote_form/", Vote.form, name="vote_form"),
]

bricolle_family/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.templatetags.static import static as static_url

from bricolle_family import settings
from bricolle_family.views.login import Login
from bricolle_family.views.summary import SummaryView

urlpatterns = [
    path("", SummaryView.home, name="home"),
    path("games", SummaryView.games, name="games"),
    path("more", SummaryView.more, name="more"),
    path("favicon.ico", RedirectView.as_view(url=static_url("favicon.svg"), permanent=True)),


    path("admin/", admin.site.urls),
    path("altered/", include("altered.urls")),
    path("baby_name/", include("baby_name.urls")),
    path("agathe/", include("agathe.urls")),
    path("finance_simulator/", include("finance_simulator.urls")),
    path("runeterra/", include("runeterra.urls")),
    path("civilization7/", include("civilization7.urls")),
    path("flash_cards/", include("flash_cards.urls")),
    path("login", Login.user_login, name="login"),
    path("logout", Login.user_logout, name="logout"),
    path("games_collection/", include("games_collection.urls")),
    path("documents/", include("documents.urls")),
    path("the_bazaar/", include("the_bazaar.urls")),
    path("capitalism/", include("capitalism.urls")),
    path("chess/", include("chess.urls")),
    path("seven_and_half/", include("seven_and_half.urls")),
]

if settings.ENV == 'local':
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chess/urls.py
from django.urls import path

from chess.views.home import home
from chess.views.openings import openings_config

app_name = "chess"

urlpatterns = [
    path("", home, name="home"),
    path("openings/", openings_config, name="openings"),
]

helpinglouis/urls.py
from django.urls import path

from . import views

app_name = "helpinglouis"

urlpatterns = [
    path("", views.index, name="index"),
    path("interface/", views.interface, name="interface"),
    path("vote/", views.vote, name="vote"),
    path("results/", views.results, name="results"),
    path("register/", views.register, name="register"),
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("helpinglouis/", include("helpinglouis.urls")),
    path('admin/', admin.site.urls),
]

baby_name/forms/evaluation.py
from django import forms

from baby_name.models import Evaluation


class EvaluationForm(forms.ModelForm):
    class Meta:
        model = Evaluation
        fields = ['name', 'score']
        widgets = {
            'name': forms.Select(attrs={'class': 'form-select'}),
            'score': forms.Select(attrs={'class': 'form-select'}),
        }
        labels = {
            'name': 'Prénom',
            'score': 'Vote',
        }

agathe/views/home.py
from django.shortcuts import redirect, render
from django.utils import timezone
import calendar
from datetime import datetime, timedelta

from agathe.constants.agathe import AgatheConstant
from agathe.models import PitStop, DiaperChange, VitaminIntake, Bath
from agathe.forms.pit_stop import PitStopForm


class HomeController:
    @staticmethod
    def home(request):
        if request.method == "POST":
            form = PitStopForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect("agathe:home")
        else:
            now = timezone.now()
            form = PitStopForm(
                initial={
                    "start_date": now.strftime("%Y-%m-%dT%H:%M"),
                }
            )

        last_pit_stop = PitStop.objects.order_by("-start_date").first()
        last_diaper_change = DiaperChange.objects.order_by("-date").first()
        diaper_overdue = False
        if last_diaper_change:
            diaper_overdue = timezone.now() - last_diaper_change.date > timedelta(hours=24)
        vitamin_today = VitaminIntake.objects.filter(
            date__date=timezone.now().date()
        ).exists()
        last_bath = Bath.objects.order_by("-date").first()
        today = timezone.now().date()
        bath_recent = last_bath and (today - last_bath.date.date()).days <= 2
        birthdate = datetime.strptime(AgatheConstant.BIRTHDATE, "%Y-%m-%d").date()
        months = (today.year - birthdate.year) * 12 + today.month - birthdate.month
        if today.day < birthdate.day:
            months -= 1
            prev_month = today.month - 1 if today.month > 1 else 12
            prev_year = today.year if today.month > 1 else today.year - 1
            days_in_prev_month = calendar.monthrange(prev_year, prev_month)[1]
            days = today.day + days_in_prev_month - birthdate.day
        else:
            days = today.day - birthdate.day
        return render(
            request,
            "agathe/home.html",
            {
                "last_pit_stop": last_pit_stop,
                "last_diaper_change": last_diaper_change,
                "diaper_overdue": diaper_overdue,
                "vitamin_today": vitamin_today,
                "last_bath": last_bath,
                "bath_recent": bath_recent,
                "age_months": months,
                "age_days": days,
                "pit_stop_form": form,
        },
        )

baby_name/views/add_name.py
from django.shortcuts import render, redirect

from baby_name.forms.name import NameForm


def add_name(request):
    if request.method == 'POST':
        form = NameForm(request.POST)
        if form.is_valid():
            name = form.save()
            name.source = request.user.username
            name.save()
            return redirect('baby_name:vote_form')
        else:
            return render(
                request,
                "baby_name/error.html",
                {"message": "Name already present in database"}
            )
    else:
        form = NameForm()
    return render(request, 'baby_name/add_name.html', {'form': form})

baby_name/views/epuration.py
from django.shortcuts import render

from baby_name.models import Evaluation
from baby_name.repositories.evaluation import EvaluationRepository
from core.repositories.user import UserRepository


def user_epuration(request):
    eval_positive_by_user = EvaluationRepository.get_all_positive_vote_user(request.user)
    name_positive_by_user = [evaluation.name for evaluation in eval_positive_by_user]
    boys_name = [name for name in name_positive_by_user if name.sex is False]
    girls_name = [name for name in name_positive_by_user if name.sex is True]

    family_members = UserRepository.get_family_members(request.user)
    other_user = family_members.exclude(id=request.user.id).first()

    epuration_boys = Evaluation.objects.filter(
        name__in=boys_name,
        user=other_user   
    ).order_by('elo')[:15]

    epuration_girls = Evaluation.objects.filter(
        name__in=girls_name,
        user=other_user   
    ).order_by('elo')[:15]

    context = {
        "epuration_boys": epuration_boys,
        "epuration_girls": epuration_girls,
    }

    return render(request, "baby_name/epuration.html", context)

baby_name/views/evaluation.py
import json

from django.http import JsonResponse, HttpResponseBadRequest
from django.shortcuts import get_object_or_404, render, redirect

from baby_name.constants.name_choice import NameChoice
from baby_name.forms.evaluation import EvaluationForm
from baby_name.models import Name, Evaluation


class EvaluationController:
    @staticmethod
    def get_or_update(request):
        if request.method == 'POST':
            form = EvaluationForm(request.POST)
            if form.is_valid():
                name = form.cleaned_data['name']
                score = form.cleaned_data['score']
                user = request.user

                evaluation, _created = Evaluation.objects.get_or_create(
                    name=name,
                    user=user,
                    defaults={'score': score}
                )

                evaluation.score = score
                evaluation.save()

                return redirect('baby_name:results')
            else:
                return render(
                    request,
                    "baby_name/error.html",
                    {"message": "Unknown Error"}
                )
        else:
            form = EvaluationForm()
        return render(request, 'baby_name/evaluation_form.html', {'form': form})

    @staticmethod
    def delete(request):
        try:
            data = json.loads(request.body)
            name_id = data.get('name_id')
            if not name_id:
                return JsonResponse({"status": "error", "message": "Missing name_id."}, status=400)

            name = get_object_or_404(Name, id=name_id)
            evaluation = Evaluation.objects.get(
                name=name,
                user=request.user,
            )
            evaluation.score = NameChoice.NON.value
            evaluation.save()

            return JsonResponse({"status": "success", "message": "Course removed."})

        except json.JSONDecodeError:
            return HttpResponseBadRequest("Invalid JSON.")

baby_name/views/global_leaderboard.py
from django.shortcuts import render

from baby_name.constants.computation_system import ComputationSystem
from baby_name.services.global_ranking import GlobalRanking


def global_leaderboard(request):
    rankings = {True: {}, False: {}}
    scoring_system = [
        ComputationSystem.SQUARE,
        ComputationSystem.FLAT,
        ComputationSystem.ELO,
    ]
    for sex in [True, False]:
        for system in scoring_system:
            ranking = GlobalRanking(
                sex=sex,
                user=request.user,
                computation_system=system
            )
            ranking.generate_ranking()
            names = ranking.extract_best_name(10)
            rankings[sex][system.value] = names

    context = {
        'male_rankings': rankings[False],
        'female_rankings': rankings[True],
    }

    return render(request, "baby_name/global_leaderboard.html", context)

baby_name/views/home.py
from django.shortcuts import render


def home(request):
    return render(request, "baby_name/home.html")

baby_name/views/leaderboard.py
from django.contrib.auth.models import User
from django.shortcuts import render

from baby_name.models import Evaluation


def leaderboard(request):
    all_users = User.objects.all()
    rankings_boys = {}
    rankings_girls = {}

    for username in all_users:
        user = User.objects.filter(username=username).first()
        rankings_boys[username] = Evaluation.objects.filter(
            user=user,
            name__sex=False,
            nb_duels__gte=3,
            elo__gte=1000,
        ).order_by('-elo')[:15]

        rankings_girls[username] = Evaluation.objects.filter(
            user=user,
            name__sex=True,
            nb_duels__gte=3,
            elo__gte=1000,
        ).order_by('-elo')[:15]

    context = {
        "rankings_boys": rankings_boys,
        "rankings_girls": rankings_girls,
    }

    return render(request, "baby_name/leaderboard.html", context)

baby_name/views/ranking.py
from urllib.parse import urlencode

from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse

from baby_name.exceptions.name_duel import NameDuelException
from baby_name.models import Evaluation
from baby_name.services.name_duel import NameDuel


class Ranking:
    @staticmethod
    def form(request):
        try:
            gender_filter = request.GET.get("gender", "all")
            name_1, name_2 = NameDuel(
                request.user,
                gender_filter=gender_filter
            ).get_names()
        except NameDuelException as exception:
            return render(
                request,
                "baby_name/error.html",
            {"message": "Moins de 2 prénoms ont été choisis, retournez en ajouter"}
            )

        context = {
            "name_1": name_1,
            "name_2": name_2,
            "gender_filter": gender_filter,
        }
        return render(request, "baby_name/ranking.html", context)

    @staticmethod
    def post(request):
        winner_id = request.POST.get('winner_id')
        loser_id = request.POST.get('loser_id')
        gender_filter = request.POST.get("gender", "all")

        winner_eval = get_object_or_404(Evaluation, name__id=winner_id, user=request.user)
        loser_eval = get_object_or_404(Evaluation, name__id=loser_id, user=request.user)

        winner_eval.win_game(loser_eval)
        loser_eval.lose_game(winner_eval)

        query = urlencode({"gender": gender_filter})
        return redirect(f"{reverse('baby_name:ranking')}?{query}")

baby_name/views/results.py
from django.shortcuts import render

from baby_name.models import Name


def results(request):
    name_coup_de_coeur_list_boys = Name.objects.filter(
        evaluations__score="coup_de_coeur",
        evaluations__user=request.user,
        sex=False
    ).distinct()

    name_coup_de_coeur_list_girls = Name.objects.filter(
        evaluations__score="coup_de_coeur",
        evaluations__user=request.user,
        sex=True
    ).distinct()

    name_yes_list_boys = Name.objects.filter(
        evaluations__score="oui",
        evaluations__user=request.user,
        sex=False
    ).distinct()
    name_yes_list_girls = Name.objects.filter(
        evaluations__score="oui",
        evaluations__user=request.user,
        sex=True
    ).distinct()

    context = {
        "name_coup_de_coeur_list_boys": name_coup_de_coeur_list_boys,
        "name_coup_de_coeur_list_girls": name_coup_de_coeur_list_girls,
        "name_yes_list_boys": name_yes_list_boys,
        "name_yes_list_girls": name_yes_list_girls,
    }
    return render(request, "baby_name/results.html", context)

baby_name/views/scripts.py
from django.shortcuts import render

from baby_name.forms.mass_yes import MassYesForm
from baby_name.services.mass_yes import MassYesService


class ScriptController:
    @staticmethod
    def glossary(request):
        return render(request, "baby_name/scripts_home.html")

    @staticmethod
    def mass_yes(request):
        form = MassYesForm(request.POST or None)
        mass_yes_result = None
        is_submitted = False

        if request.method == "POST":
            is_submitted = True
            if form.is_valid():
                service = MassYesService()
                mass_yes_result = service.execute(
                    raw_names=form.cleaned_data["names"],
                    family=form.cleaned_data["family"],
                    source_name=request.user.username,
                    sex=form.cleaned_data["sex"],
                )

        context = {
            "form": form,
            "mass_yes_result": mass_yes_result,
            "is_submitted": is_submitted,
        }
        return render(request, "baby_name/scripts_mass_yes.html", context)

baby_name/views/user_leaderboard.py
from django.shortcuts import render

from baby_name.models import Evaluation
from core.repositories.user import UserRepository


def user_leaderboard(request):
    family_members = UserRepository.get_family_members(request.user)
    rankings_boys = {}
    rankings_girls = {}

    for user in family_members:
        rankings_boys[user] = Evaluation.objects.filter(
            user=user,
            name__sex=False,
            elo__gte=1001,
        ).order_by('-elo')[:15]

        rankings_girls[user] = Evaluation.objects.filter(
            user=user,
            name__sex=True,
            elo__gte=1001,
        ).order_by('-elo')[:15]

    context = {
        "rankings_boys": rankings_boys,
        "rankings_girls": rankings_girls,
    }

    return render(request, "baby_name/user_leaderboard.html", context)

baby_name/templates/baby_name/add_name.html
{% extends 'baby_name/base.html' %}


{% block title %}Add Name{% endblock %}

{% block content %}
    <h2 class="mb-4">Ajouter un prénom</h2>
    <form method="post" class="card p-4 shadow-sm">
        {% csrf_token %}
        <div class="mb-3">
            {{ form.name.label_tag }}
            {{ form.name }}
        </div>
        <div class="mb-3">
            {{ form.sex.label_tag }}
            {{ form.sex }}
        </div>
        <hr class="my-4">
        <div class="mb-3">
            {{ form.tag.label_tag }}
            {{ form.tag }}
        </div>
        <button type="submit" class="btn btn-primary">Ajouter</button>
    </form>
{% endblock %}

baby_name/templates/baby_name/base.html
{% load static %}
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prénoms</title>

    <link rel="stylesheet" href="{% static 'baby_name/style.css' %}">

    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">

</head>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const elements = document.querySelectorAll(".name-text");

        elements.forEach(el => {
            let fontSize = 80;

            el.style.fontSize = fontSize + "px";

            while (
                (el.scrollWidth > el.offsetWidth || el.scrollHeight > el.offsetHeight) &&
                fontSize > 20
                ) {
                fontSize -= 1;
                el.style.fontSize = fontSize + "px";
            }
        });
    });
</script>

<body>

<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light px-3">
        <div class="container-fluid">

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMenu"
                    aria-controls="navbarMenu" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarMenu">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'baby_name:home' %}">Accueil</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'baby_name:vote_form' %}">🗳️ Vote</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'baby_name:results' %}">📋 Vos prénoms</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'baby_name:evaluation_update' %}">🔄 Changer Vote</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'baby_name:ranking' %}">⚔️ Duels</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'baby_name:user_leaderboard' %}">📊 Classements par user</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'baby_name:global_leaderboard' %}">🏆 Classements général</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'baby_name:add_name' %}">🆕 Nouveau nom</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'baby_name:epuration' %}">🧹 La purge</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'baby_name:scripts_home' %}">🛠️ Scripts</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>

<div class="container">
    {% block content %}
    {% endblock %}
</div>

{% block extra_scripts %}
{% endblock %}
<script src="{% static 'keystrokes.js' %}"></script>

baby_name/templates/baby_name/home.html
{% extends 'baby_name/base.html' %}
{% block content %}
    <div class="container py-5">
        <h1 class="mb-4 text-center">Bienvenue sur le projet Prénoms {{ request.user.username }}👶</h1>

        <p class="lead">Ce site vous aide à trouver un prénom qui plaît à toute la famille. Voici les différentes étapes
            :</p>

        <div class="row">
            <div class="col-md-6 mb-4">
                <a href="{% url 'baby_name:vote_form' %}" class="text-decoration-none text-reset">
                    <div class="card shadow-sm h-100">
                        <div class="card-body">
                            <h5 class="card-title">🗳️ <strong>Vote</strong></h5>
                            <p class="card-text">La première page à consulter. Vous notez les prénoms en indiquant s’ils
                                vous déplaisent, plaisent ou sont un coup de cœur.</p>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-6 mb-4">
                <a href="{% url 'baby_name:results' %}" class="text-decoration-none text-reset">
                    <div class="card shadow-sm h-100">
                        <div class="card-body">
                            <h5 class="card-title">📋 <strong>Vos prénoms</strong></h5>
                            <p class="card-text">Un résumé de vos prénoms préférés, vous pourrez aussi enlever les noms
                                qui vous plaisent moins après réflexion</p>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-6 mb-4">
                <a href="{% url 'baby_name:evaluation_update' %}" class="text-decoration-none text-reset">
                    <div class="card shadow-sm h-100">
                        <div class="card-body">
                            <h5 class="card-title">🔄 <strong>Changer Vote</strong></h5>
                            <p class="card-text">Il vous permet de changer d'avis sur un prénom ou de faire un vote
                                précis sans attendre de tomber dessus pas hasard dans la page vote.</p>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-6 mb-4">
                <a href="{% url 'baby_name:ranking' %}" class="text-decoration-none text-reset">
                    <div class="card shadow-sm h-100">
                        <div class="card-body">
                            <h5 class="card-title">⚔️ <strong>Duels</strong></h5>
                            <p class="card-text">Le site vous propose deux prénoms que quelqu’un de votre famille aime.
                                Choisissez celui que vous préférez.</p>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-6 mb-4">
                <a href="{% url 'baby_name:user_leaderboard' %}" class="text-decoration-none text-reset">
                    <div class="card shadow-sm h-100">
                        <div class="card-body">
                            <h5 class="card-title">📊 <strong>Classements par utilisateur</strong></h5>
                            <p class="card-text">Consultez votre propre classement des prénoms, basé sur vos votes et
                                vos
                                duels.</p>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-6 mb-4">
                <a href="{% url 'baby_name:global_leaderboard' %}" class="text-decoration-none text-reset">
                    <div class="card shadow-sm h-100">
                        <div class="card-body">
                            <h5 class="card-title">🏆 <strong>Classement général</strong></h5>
                            <p class="card-text">Découvrez le classement familial global des prénoms, selon plusieurs
                                méthodes de calcul.</p>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-6 mb-4">
                <a href="{% url 'baby_name:add_name' %}" class="text-decoration-none text-reset">
                    <div class="card shadow-sm h-100">
                        <div class="card-body">
                            <h5 class="card-title">🆕 <strong>Ajouter un nom</strong></h5>
                            <p class="card-text">Ajoute un nouveau prénom que tu ne trouves pas dans la base</p>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-6 mb-4">
                <a href="{% url 'baby_name:epuration' %}" class="text-decoration-none text-reset">
                    <div class="card shadow-sm h-100">
                        <div class="card-body">
                            <h5 class="card-title">🧹 <strong>La purge</strong></h5>
                            <p class="card-text">Affiche les prénoms que vous aimez mais qui sont moins populaires
                                auprès de
                                la famille. Utile pour converger vers un consensus !</p>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-6 mb-4">
                <a href="{% url 'baby_name:scripts_home' %}" class="text-decoration-none text-reset">
                    <div class="card shadow-sm h-100">
                        <div class="card-body">
                            <h5 class="card-title">🛠️ <strong>Scripts</strong></h5>
                            <p class="card-text">Regroupe des outils d'actions en masse pour accélérer la gestion des prénoms.</p>
                        </div>
                    </div>
                </a>
            </div>
        </div>

        <hr class="my-5">

        <h2 class="mb-3">❓ Q&A</h2>

        <ul class="list-group mb-4">
            <li class="list-group-item">
                <strong>Pourquoi aucun prénom n'apparaît dans le classement général ?</strong><br>
                Parce que vous n’avez pas encore voté sur les prénoms aimés par le reste de votre famille. Allez sur
                <strong>Vote</strong>, commencez par les prénoms filles, puis garçons.
            </li>
            <li class="list-group-item">
                <strong>Il manque des prénoms ?</strong><br>
                Envoyez-moi une liste de prénoms que vous aimez ou une source/base, je les ajouterai manuellement.
            </li>
        </ul>

        <hr class="my-5">

        <h2 class="mb-3">🚧 Fonctionnalités à venir</h2>

        <ul class="list-group mb-4">
            <li class="list-group-item">
                💡 <strong>Envie de proposer une fonctionnalité ?</strong><br>
                Si vous avez une idée pour améliorer le site, n’hésitez pas à l’envoyer à Louis ou Cécile (aka le couple
                Bricolle 🛠️❤️).
            </li>
        </ul>

        <p class="text-muted text-center">
            Ce projet est en évolution constante. Vos retours sont précieux 🙌
        </p>
    </div>

{% endblock %}

baby_name/templates/baby_name/interface.html
{% extends 'baby_name/base.html' %}
{% block content %}

<div class="container d-flex justify-content-center align-items-center mt-2 mb-3">
    <form method="post" action="{% url 'baby_name:interface' %}">
        {% csrf_token %}
        <button type="submit" name="gender" value="all"
            class="btn btn-link filter-btn {% if gender_filter == 'all' %}selected{% endif %}">
            All
        </button>

        <button type="submit" name="gender" value="boys" 
            class="btn btn-link filter-btn {% if gender_filter == 'boys' %}selected{% endif %}">
            Boys
        </button>

        <button type="submit" name="gender" value="girls" 
            class="btn btn-link filter-btn {% if gender_filter == 'girls' %}selected{% endif %}">
            Girls
        </button>
    </form>
</div>

<div class="container d-flex justify-content-center align-items-center">
    <div class="card custom-rounded shadow" style="width: 27rem; height: 33rem">
        <div class="card-body text-center d-flex flex-column justify-content-between">
            <div class="text-center">
                {% if name %}
                    <h1 class="{% if name.sex %}custom-name-girl{% else %}custom-name-boy{% endif %}" style="margin-top: 120px;">{{ name.name }}</h1>
                {% else %}
                    <h1 class="text-muted mt-5">No names available.</h1>
                {% endif %}
            </div>
            <div>
                {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>
                 {% endif %}
            </div>

            <form action="{% url 'baby_name:vote' %}" method="post">
                {% csrf_token %}
   
                <fieldset class="vote-buttons d-flex justify-content-center align-items-center gap-4" style="margin-bottom: 30px;">
                    <button type="submit" name="score" value="non" class="vote-btn btn-dislike">
                        <i class="fas fa-times"></i>
                    </button>

                    <button type="submit" name="score" value="coup_de_coeur" class="vote-btn btn-neutral">
                        <i class="fas fa-heart"></i>
                    </button>

                    <button type="submit" name="score" value="oui" class="vote-btn btn-like">
                        <i class="fas fa-check"></i>
                    </button>
                    <input type="hidden" name="name_id" value="{{ name.id }}">
                    <input type="hidden" name="gender" value="{{ gender_filter }}"> 
                </fieldset>
            </form> 
        </div>
    </div>
</div>
{% endblock %}