chess/urls.py
from django.urls import path

from chess.views.home import home
from chess.views.openings import openings_config

app_name = "chess"

urlpatterns = [
    path("", home, name="home"),
    path("openings/", openings_config, name="openings"),
]

documents/urls.py
from django.urls import path

from documents.views import (
    document_list,
    document_detail,
    DocumentCreateView,
    DocumentUpdateView,
)

app_name = "documents"

urlpatterns = [
    path("", document_list, name="document_list"),
    path("new/", DocumentCreateView.as_view(), name="document_create"),
    path("<int:pk>/", document_detail, name="document_detail"),
    path("<int:pk>/edit/", DocumentUpdateView.as_view(), name="document_edit"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("helpinglouis/", include("helpinglouis.urls")),
    path('admin/', admin.site.urls),
]

runeterra/urls.py
from django.urls import path

from runeterra import views

app_name = "runeterra"

urlpatterns = [
    path("", views.random_picker, name="random_picker"),
    path("objectives/", views.objectives, name="objectives"),
    path("ideas/", views.ideas, name="ideas"),
    path("stats/", views.region_stats, name="region_stats"),
    path("monthly-challenge/", views.monthly_challenge, name="monthly_challenge"),
    path("champions/", views.champion_list, name="champion_list"),
    path("champions/new/", views.ChampionCreateView.as_view(), name="champion_create"),
    path("champions/<int:pk>/edit/", views.ChampionUpdateView.as_view(), name="champion_update"),
]

altered/models/champion.py
from django.contrib import admin
from django.db import models

from altered.constants.faction import Faction


class Champion(models.Model):
    name = models.CharField(
        max_length=32,
    )
    faction = models.CharField(
        max_length=8,
        choices=Faction.choices,
    )

    def __str__(self):
        return f"{self.name} ({self.faction})"


@admin.register(Champion)
class ChampionAdmin(admin.ModelAdmin):
    list_display = ('name', 'faction',)
    list_filter = ('faction',)
    ordering = ('name',)

runeterra/models/champion.py
from django.contrib import admin
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from runeterra.constants.region import Region


class Champion(models.Model):
    name = models.CharField(max_length=255, unique=True)
    primary_region = models.CharField(max_length=20, choices=Region.choices)
    secondary_region = models.CharField(
        max_length=20, choices=Region.choices, blank=True, null=True
    )
    star_level = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(7)])
    champion_level = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(60)])
    monthly_try_remaining = models.IntegerField(
        default=3,
        validators=[MinValueValidator(0), MaxValueValidator(3)],
    )
    unlocked = models.BooleanField(default=False)
    lvl30 = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.set_lvl30()
        super().save(*args, **kwargs)

    def set_lvl30(self):
        if self.champion_level >= 30:
            self.lvl30 = True
        else:
            self.lvl30 = False

    def __str__(self):
        return self.name

    @property
    def monthly_is_available(self):
        return self.monthly_try_remaining > 0 and self.star_level >= 2


@admin.register(Champion)
class ChampionAdmin(admin.ModelAdmin):
    list_display = (
        "name",
        "primary_region",
        "secondary_region",
        "star_level",
        "monthly_try_remaining",
        "unlocked",
        "lvl30",
    )
    list_filter = ("primary_region", "secondary_region", "unlocked", "lvl30")
    search_fields = ("name",)

documents/forms/document.py
from django import forms

from documents.models import Document


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ["title", "directory", "content"]
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control"}),
            "directory": forms.Select(attrs={"class": "form-select"}),
            "content": forms.Textarea(attrs={"class": "form-control", "rows": 10}),
        }
        labels = {
            "title": "Titre",
            "directory": "Catégorie",
            "content": "Contenu",
        }

agathe/views/documents.py
from documents.constants.directories import Directories
from documents.views import render_document


class DocumentController:
    @staticmethod
    def _render_document(request, title: str):
        return render_document(
            request,
            title=title,
            directory=Directories.AGATHE,
            template_name="agathe/document.html",
        )

    @staticmethod
    def question_to_ask(request):
        return DocumentController._render_document(request, "Question à poser")

    @staticmethod
    def next_evolution_milestone(request):
        return DocumentController._render_document(request, "Next évolution milestone")

    @staticmethod
    def website_ideas(request):
        return DocumentController._render_document(request, "Website Ideas")

capitalism/views/documents.py
from documents.constants.directories import Directories
from documents.views import render_document


class CapitalismDocumentView:
    template_name = "capitalism/document.html"

    @staticmethod
    def idea(request):
        return render_document(
            request,
            title="Simulation Ideas",
            directory=Directories.CAPITALISM,
            template_name=CapitalismDocumentView.template_name,
            include_edit_url=True,
        )

documents/views/document.py
from typing import Any, Dict, Optional

from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView
from django.utils.safestring import mark_safe
import markdown
from urllib.parse import urlencode

from documents.constants.directories import Directories
from documents.forms import DocumentForm
from documents.models import Document


DEFAULT_REDIRECT_FIELD_NAME = "next"


def render_document(
    request,
    *,
    title: str,
    directory: Directories,
    template_name: str,
    extra_context: Optional[Dict[str, Any]] = None,
    include_edit_url: bool = False,
    redirect_to: Optional[str] = None,
    redirect_field_name: str = DEFAULT_REDIRECT_FIELD_NAME,
):
    """Render a document page by loading Markdown content and optional edit link."""

    document, _ = Document.objects.get_or_create(
        title=title,
        directory=directory,
        defaults={"content": ""},
    )
    content_html = mark_safe(markdown.markdown(document.content))

    context: Dict[str, Any] = {
        "title": title,
        "content_html": content_html,
        "document": document,
    }
    if extra_context:
        context.update(extra_context)

    if include_edit_url:
        if redirect_to is None:
            redirect_to = request.get_full_path()
        edit_url = reverse("documents:document_edit", args=[document.pk])
        if redirect_to:
            edit_url = f"{edit_url}?{urlencode({redirect_field_name: redirect_to})}"
        context["edit_url"] = edit_url

    return render(request, template_name, context)


def document_list(request):
    documents = Document.objects.all().order_by("title")

    directory = request.GET.get("directory")
    query = request.GET.get("q")

    if directory:
        documents = documents.filter(directory=directory)
    if query:
        documents = documents.filter(
            Q(title__icontains=query) | Q(content__icontains=query)
        )

    return render(
        request,
        "documents/document_list.html",
        {"documents": documents, "directories": Directories},
    )


def document_detail(request, pk):
    document = get_object_or_404(Document, pk=pk)
    content_html = mark_safe(markdown.markdown(document.content))
    return render(
        request,
        "documents/document_detail.html",
        {"document": document, "content_html": content_html},
    )


class DocumentCreateView(CreateView):
    model = Document
    form_class = DocumentForm
    template_name = "documents/document_form.html"
    success_url = reverse_lazy("documents:document_list")


class DocumentUpdateView(UpdateView):
    model = Document
    form_class = DocumentForm
    template_name = "documents/document_form.html"
    success_url = reverse_lazy("documents:document_list")
    redirect_field_name = DEFAULT_REDIRECT_FIELD_NAME

    def _get_redirect_to(self):
        return self.request.POST.get(self.redirect_field_name) or self.request.GET.get(
            self.redirect_field_name
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        redirect_to = self._get_redirect_to()
        if redirect_to:
            context["redirect_to"] = redirect_to
            context["redirect_field_name"] = self.redirect_field_name
        return context

    def get_success_url(self):
        redirect_to = self._get_redirect_to()
        if redirect_to:
            return redirect_to
        return super().get_success_url()

finance_simulator/views/documents.py
from documents.constants.directories import Directories
from documents.views import render_document


def _render_document(request, title: str):
    return render_document(
        request,
        title=title,
        directory=Directories.FINANCE_SIMULATOR,
        template_name="finance_simulator/document.html",
    )


def ideas(request):
    return _render_document(request, "Ideas")

runeterra/views/champion.py
from django.db.models import Q
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from runeterra.constants.region import Region
from runeterra.forms.champion import ChampionForm
from runeterra.models import Champion


def champion_list(request):
    champions = Champion.objects.all()

    region = request.GET.get("region", "")
    star_level = request.GET.get("star_level")
    only_unlocked = request.GET.get("only_unlocked") is not None
    only_lvl30 = request.GET.get("only_lvl30") is not None
    sort = request.GET.get("sort", "name")

    if region:
        champions = champions.filter(
            Q(primary_region=region) | Q(secondary_region=region)
        )
    if star_level:
        try:
            star_level_value = int(star_level)
            champions = champions.filter(star_level__gte=star_level_value)
        except (TypeError, ValueError):
            pass
    if only_unlocked:
        champions = champions.filter(unlocked=True)
    if only_lvl30:
        champions = champions.filter(lvl30=True)

    if sort == "star_level":
        champions = champions.order_by("-star_level", "name")
    elif sort == "level":
        champions = champions.order_by("-champion_level", "name")
    else:
        champions = champions.order_by("name")

    return render(
        request,
        "runeterra/champion_list.html",
        {
            "champions": champions,
            "regions": Region,
        },
    )


class ChampionCreateView(CreateView):
    model = Champion
    form_class = ChampionForm
    template_name = "runeterra/champion_form.html"
    success_url = reverse_lazy("runeterra:champion_list")


class ChampionUpdateView(UpdateView):
    model = Champion
    form_class = ChampionForm
    template_name = "runeterra/champion_form.html"
    success_url = reverse_lazy("runeterra:champion_list")

runeterra/views/documents.py
from documents.constants.directories import Directories
from documents.views import render_document


def _render_document(request, title: str):
    return render_document(
        request,
        title=title,
        directory=Directories.RUNETERRA,
        template_name="runeterra/document.html",
    )


def objectives(request):
    return _render_document(request, "Objectives")


def ideas(request):
    return _render_document(request, "Ideas")

runeterra/views/monthly_challenge.py
from django.shortcuts import redirect, render

from runeterra.services.monthly_challenge import (
    MonthlyChallengeAvailableService,
    MonthlyChallengeConsumeService,
    MonthlyChallengeResetService,
)


def monthly_challenge(request):
    if request.method == "POST":
        action = request.POST.get("action")
        if action == "reset":
            MonthlyChallengeResetService().reset()
        elif action == "consume":
            champion_id = request.POST.get("champion_id")
            try:
                MonthlyChallengeConsumeService().consume(int(champion_id))
            except (TypeError, ValueError):
                pass
        return redirect("runeterra:monthly_challenge")

    star_level = request.GET.get("star_level")
    selected_star_level = None
    if star_level:
        try:
            selected_star_level = int(star_level)
        except (TypeError, ValueError):
            selected_star_level = None

    available_service = MonthlyChallengeAvailableService()
    champions, star_counts, total_available = available_service.list_available()
    if selected_star_level is None:
        for star in range(2, 8):
            if star_counts.get(star, 0) > 0:
                selected_star_level = star
                break
    if selected_star_level is not None:
        champions, _, _ = available_service.list_available(selected_star_level)
    spotlight = available_service.pick_spotlight()
    star_filters = [
        {"star": star, "count": star_counts[star]} for star in range(2, 8)
    ]
    return render(
        request,
        "runeterra/monthly_challenge.html",
        {
            "champions": champions,
            "star_filters": star_filters,
            "selected_star_level": selected_star_level,
            "total_available": total_available,
            "spotlight": spotlight,
        },
    )

runeterra/views/random.py
from django.db.models import Q
from django.shortcuts import render

from runeterra.constants.region import Region
from runeterra.models import Champion


def random_picker(request):
    champion = None
    only_unlocked = False
    only_lvl30 = False
    selected_region = ""
    min_star_level = 0
    min_level = 0
    max_level = 60

    if request.method == "POST":
        only_unlocked = bool(request.POST.get("only_unlocked"))
        only_lvl30 = bool(request.POST.get("only_lvl30"))
        selected_region = request.POST.get("region", "")
        try:
            min_star_level = int(request.POST.get("min_star_level", 0))
        except (TypeError, ValueError):
            min_star_level = 0
        try:
            min_level = int(request.POST.get("min_level", 0))
        except (TypeError, ValueError):
            min_level = 0
        try:
            max_level = int(request.POST.get("max_level", 60))
        except (TypeError, ValueError):
            max_level = 60

        queryset = Champion.objects.all()

        if only_unlocked:
            queryset = queryset.filter(unlocked=True)
        if only_lvl30:
            queryset = queryset.filter(lvl30=True)
        if selected_region:
            queryset = queryset.filter(
                Q(primary_region=selected_region) | Q(secondary_region=selected_region)
            )
        if min_star_level:
            queryset = queryset.filter(star_level__gte=min_star_level)
        if min_level:
            queryset = queryset.filter(champion_level__gte=min_level)
        if max_level:
            queryset = queryset.filter(champion_level__lte=max_level)

        champion = queryset.order_by("?").first()

    return render(
        request,
        "runeterra/random_picker.html",
        {
            "champion": champion,
            "only_unlocked": only_unlocked,
            "only_lvl30": only_lvl30,
            "selected_region": selected_region,
            "min_star_level": min_star_level,
            "min_level": min_level,
            "max_level": max_level,
            "regions": Region,
        },
    )

runeterra/views/stats.py
from django.db.models import Avg, Case, F, IntegerField, Q, When, Min, Max
from django.shortcuts import render

from runeterra.constants.region import Region
from runeterra.models import Champion


def region_stats(request):
    only_unlocked = request.GET.get("only_unlocked") is not None
    stats = []
    for value, label in Region.choices:
        base_qs = Champion.objects.filter(
            Q(primary_region=value) | Q(secondary_region=value)
        )
        total = base_qs.count()
        unlocked = base_qs.filter(unlocked=True).count()
        qs = base_qs.filter(unlocked=True) if only_unlocked else base_qs

        constellation_mean = (
            qs.annotate(
                effective=F("star_level")
                + Case(When(lvl30=True, then=2), default=0, output_field=IntegerField())
            )
            .aggregate(avg=Avg("effective"))
            .get("avg")
            or 0
        )
        level_stats = qs.aggregate(
            mean=Avg("champion_level"),
            min=Min("champion_level"),
            max=Max("champion_level"),
        )
        stats.append(
            {
                "label": label,
                "total": total,
                "unlocked": unlocked,
                "constellation_mean": constellation_mean,
                "level_mean": level_stats.get("mean") or 0,
                "level_min": level_stats.get("min") or 0,
                "level_max": level_stats.get("max") or 0,
            }
        )

    return render(
        request,
        "runeterra/region_stats.html",
        {"stats": stats, "only_unlocked": only_unlocked},
    )

runeterra/templates/runeterra/champion_edit_modal.html
<div class="modal fade" id="editChampionModal{{ champion.id }}" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Edit {{ champion.name }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="post" action="{% url 'runeterra:champion_update' champion.id %}">
                {% csrf_token %}
                <div class="modal-body">
                    <div class="mb-3">
                        <label class="form-label" for="id_name_{{ champion.id }}">Name</label>
                        <input type="text" class="form-control" id="id_name_{{ champion.id }}" name="name" value="{{ champion.name }}">
                    </div>
                    <div class="mb-3">
                        <label class="form-label" for="id_primary_region_{{ champion.id }}">Primary Region</label>
                        <select class="form-select" id="id_primary_region_{{ champion.id }}" name="primary_region">
                            {% for value, label in regions.choices %}
                                <option value="{{ value }}" {% if champion.primary_region == value %}selected{% endif %}>{{ label }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="mb-3">
                        <label class="form-label" for="id_secondary_region_{{ champion.id }}">Secondary Region</label>
                        <select class="form-select" id="id_secondary_region_{{ champion.id }}" name="secondary_region">
                            <option value=""></option>
                            {% for value, label in regions.choices %}
                                <option value="{{ value }}" {% if champion.secondary_region == value %}selected{% endif %}>{{ label }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="mb-3">
                        <label class="form-label" for="id_star_level_{{ champion.id }}">Star Level</label>
                        <input type="number" min="0" max="7" class="form-control" id="id_star_level_{{ champion.id }}" name="star_level" value="{{ champion.star_level }}">
                    </div>
                    <div class="mb-3">
                        <label class="form-label" for="id_champion_level_{{ champion.id }}">Level</label>
                        <input type="number" min="0" max="60" class="form-control" id="id_champion_level_{{ champion.id }}" name="champion_level" value="{{ champion.champion_level }}">
                    </div>
                    <div class="mb-3">
                        <label class="form-label" for="id_monthly_try_remaining_{{ champion.id }}">Monthly tries remaining</label>
                        <input type="number" min="0" max="3" class="form-control" id="id_monthly_try_remaining_{{ champion.id }}" name="monthly_try_remaining" value="{{ champion.monthly_try_remaining }}">
                    </div>
                    <div class="form-check mb-3">
                        <input class="form-check-input" type="checkbox" id="id_unlocked_{{ champion.id }}" name="unlocked" {% if champion.unlocked %}checked{% endif %}>
                        <label class="form-check-label" for="id_unlocked_{{ champion.id }}">Unlocked</label>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

runeterra/templates/runeterra/champion_list.html
{% extends 'runeterra/base.html' %}

{% block title %}Champions{% endblock %}

{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3">
    <h1 class="mb-0">Champions 🏆</h1>
    <a class="btn btn-primary" href="{% url 'runeterra:champion_create' %}">➕ Add Champion</a>
</div>
<form method="get" class="row g-3 mb-4">
    <div class="col-md-3">
        <label class="form-label" for="region">Region</label>
        <select name="region" id="region" class="form-select">
            <option value="">All regions</option>
            {% for value, label in regions.choices %}
                <option value="{{ value }}" {% if request.GET.region == value %}selected{% endif %}>{{ label }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="col-md-2">
        <label class="form-label" for="starLevel">Min star level</label>
        <input type="number" min="0" max="7" name="star_level" id="starLevel" class="form-control" value="{{ request.GET.star_level }}">
    </div>
    <div class="col-md-2 d-flex align-items-end">
        <div class="form-check">
            <input class="form-check-input" type="checkbox" name="only_unlocked" id="onlyUnlocked" {% if request.GET.only_unlocked %}checked{% endif %}>
            <label class="form-check-label" for="onlyUnlocked">Unlocked</label>
        </div>
    </div>
    <div class="col-md-2 d-flex align-items-end">
        <div class="form-check">
            <input class="form-check-input" type="checkbox" name="only_lvl30" id="onlyLvl30" {% if request.GET.only_lvl30 %}checked{% endif %}>
            <label class="form-check-label" for="onlyLvl30">Level 30</label>
        </div>
    </div>
    <div class="col-md-2">
        <label class="form-label" for="sort">Sort by</label>
        <select name="sort" id="sort" class="form-select">
            <option value="name" {% if request.GET.sort == 'name' %}selected{% endif %}>Alphabetical</option>
            <option value="star_level" {% if request.GET.sort == 'star_level' %}selected{% endif %}>Star level</option>
            <option value="level" {% if request.GET.sort == 'level' %}selected{% endif %}>Level</option>
        </select>
    </div>
    <div class="col-md-1 d-flex align-items-end">
        <button type="submit" class="btn btn-primary w-100">Filter</button>
    </div>
</form>

{% if champions %}
<table class="table table-striped">
    <thead>
    <tr>
        <th>Name</th>
        <th>Primary Region</th>
        <th>Secondary Region</th>
        <th>Stars ⭐</th>
        <th>Level</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    {% for champion in champions %}
    <tr
        {% if not champion.unlocked %}
            class="table-danger"
        {% elif champion.lvl30 %}
            class="table-success"
        {% else %}
            class="table-warning"
        {% endif %}
    >
        <td>{{ champion.name }}</td>
        <td>{{ champion.get_primary_region_display }}</td>
        <td>{{ champion.get_secondary_region_display }}</td>
        <td>{{ champion.star_level }} ⭐</td>
        <td>{{ champion.champion_level }}</td>
        <td>
            <button type="button" class="btn btn-sm btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#editChampionModal{{ champion.id }}">🖊️</button>
        </td>
    </tr>
    {% include 'runeterra/champion_edit_modal.html' %}
    {% endfor %}
    </tbody>
</table>
{% else %}
<p>No champions found.</p>
{% endif %}
{% endblock %}

runeterra/templates/runeterra/document.html
{% extends 'runeterra/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h1>{{ title }}</h1>
    <div class="mt-4">{{ content_html }}</div>
{% endblock %}

runeterra/templates/runeterra/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light px-3">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'runeterra:random_picker' %}">Runeterra ⚔️</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        <ul class="navbar-nav me-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'runeterra:random_picker' %}">Random Picker</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'runeterra:champion_list' %}">Champions</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'runeterra:region_stats' %}">Region Stats</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'runeterra:monthly_challenge' %}">Monthly Challenge</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'runeterra:objectives' %}">Objectives</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'runeterra:ideas' %}">Ideas</a>
            </li>
        </ul>
    </div>
</nav>

runeterra/templates/runeterra/random_picker.html
{% extends 'runeterra/base.html' %}

{% block title %}Random Picker{% endblock %}

{% block content %}
    <h1 class="mb-4">Random Champion Picker 🎲</h1>
    <div class="row">
        <div class="col-md-4">
            <form method="post" class="mb-4">
                {% csrf_token %}
                <div class="form-check mb-2">
                    <input
                        class="form-check-input"
                        type="checkbox"
                        name="only_unlocked"
                        id="onlyUnlocked"
                        {% if only_unlocked %}checked{% endif %}
                    >
                    <label class="form-check-label" for="onlyUnlocked">
                        Only unlocked
                    </label>
                </div>
                <div class="form-check mb-3">
                    <input
                        class="form-check-input"
                        type="checkbox"
                        name="only_lvl30"
                        id="onlyLvl30"
                        {% if only_lvl30 %}checked{% endif %}
                    >
                    <label class="form-check-label" for="onlyLvl30">
                        Only level 30
                    </label>
                </div>
                <div class="mb-3">
                    <label class="form-label" for="region">Region</label>
                    <select name="region" id="region" class="form-select">
                        <option value="">All regions</option>
                        {% for value, label in regions.choices %}
                            <option value="{{ value }}" {% if selected_region == value %}selected{% endif %}>{{ label }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="mb-3">
                    <label class="form-label" for="minStarLevel">Minimum star level</label>
                    <input
                        type="number"
                        name="min_star_level"
                        id="minStarLevel"
                        class="form-control"
                        min="0"
                        max="7"
                        value="{{ min_star_level }}"
                    >
                </div>
                <div class="mb-3">
                    <label class="form-label" for="minLevel">Min level</label>
                    <input
                        type="number"
                        name="min_level"
                        id="minLevel"
                        class="form-control"
                        min="0"
                        max="60"
                        value="{{ min_level }}"
                    >
                </div>
                <div class="mb-3">
                    <label class="form-label" for="maxLevel">Max level</label>
                    <input
                        type="number"
                        name="max_level"
                        id="maxLevel"
                        class="form-control"
                        min="0"
                        max="60"
                        value="{{ max_level }}"
                    >
                </div>
                <button type="submit" class="btn btn-primary">Pick a Champion</button>
            </form>
        </div>
        <div class="col-md-8">
            {% if champion %}
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-start">
                            <h3 class="card-title mb-0">{{ champion.name }}</h3>
                            <button type="button" class="btn btn-sm btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#editChampionModal{{ champion.id }}">🖊️</button>
                        </div>
                        <p class="card-text">Primary Region: {{ champion.get_primary_region_display }}</p>
                        {% if champion.secondary_region %}
                            <p class="card-text">Secondary Region: {{ champion.get_secondary_region_display }}</p>
                        {% endif %}
                        <p class="card-text">Star Level: {{ champion.star_level }} ⭐</p>
                        <p class="card-text">Level: {{ champion.champion_level }}</p>
                    </div>
                </div>
                {% include 'runeterra/champion_edit_modal.html' %}
            {% elif request.method == 'POST' %}
                <p class="mt-4">No champion matches your criteria.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}